site_name: Lily's Tech Blog
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
      primary: teal
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Light mode
      primary: teal
      accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/witchessabath
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/lilymightbyte

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - awesome-pages

copyright: |
 &copy; 2024 <a href="https://github.com/witchessabath" target="_blank" rel="noopener">Lily Sabath</a>